version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "vparrot.settings"
    volumes:
      - .:/app
