name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vparrot-garage-django:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vparrot-garage-django:latest

      - name: Deploy to EC2
        run: |
          printf "%s" "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/ci_key.pem
          chmod 600 /tmp/ci_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/ci_key.pem ec2-user@44.211.213.182 <<EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/vparrot-garage-django:latest
            docker ps --filter "name=django-container" --quiet | xargs -r docker stop || true
            docker ps --filter "name=django-container" --quiet | xargs -r docker rm || true
            docker run -d --name django-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/vparrot-garage-django:latest
          EOF
          rm -f /tmp/ci_key.pem


